defmodule Canopy.Provenance.OxigraphEmitter do
  @moduledoc """
  Provenance tracking to Oxigraph for Canopy artifacts.

  Implements the Chatman Equation A=μ(O): artifacts are projections of ontologies
  via transformation functions. Every artifact generated by Canopy agent execution
  is recorded as a PROV-O triple in Oxigraph.

  Emits three key operations:
    1. emit_activity/2 - Record an agent or system action
    2. emit_artifact/2 - Record an artifact (result, output, decision)
    3. emit_derivation/3 - Link artifact to activity that generated it

  All operations have explicit timeout_ms with fallback (WvdA Soundness).

  Signal Theory: S=(provenance,audit,record,ttl,rdf)
  """

  require Logger

  @default_timeout_ms 5000
  @oxigraph_url System.get_env("OXIGRAPH_URL") || "http://localhost:7878"

  @doc """
  Emit an activity record for an agent or system action.

  Records a PROV-O Activity triple: when an agent executes a task, query, or decision.

  ## Parameters:
    - activity_id: unique ID for the activity (e.g., "agent_7_task_12345")
    - details: map with keys:
      - :agent_id - ID of agent performing action (required)
      - :action_type - type of action (required, e.g., "task_execution", "decision", "healing")
      - :timestamp - ISO8601 timestamp (optional, defaults to now)
      - :duration_ms - elapsed time (optional)
      - :status - "ok" or "error" (optional)
      - :input - input parameters (optional)
      - :output - result/output (optional)

  Returns :ok or {:error, reason}

  Example:
    emit_activity("agent_7_task_1", %{
      agent_id: "agent_7",
      action_type: "task_execution",
      duration_ms: 245,
      status: "ok"
    })
  """
  @spec emit_activity(String.t(), map()) :: :ok | {:error, term()}
  def emit_activity(activity_id, details) do
    timeout = Keyword.get([timeout: @default_timeout_ms], :timeout, @default_timeout_ms)

    task =
      Task.Supervisor.async_nolink(Canopy.TaskSupervisor, fn ->
        do_emit_activity(activity_id, details, timeout)
      end)

    case Task.yield(task, timeout + 1000) do
      {:ok, result} ->
        result

      nil ->
        Task.shutdown(task, :brutal_kill)
        Logger.error("[OxigraphEmitter] Activity emission timed out: #{activity_id}")
        {:error, :timeout}
    end
  end

  @doc """
  Emit an artifact record (result, output, document, decision).

  Records a PROV-O Entity triple: when a system or agent creates an artifact.

  ## Parameters:
    - artifact_id: unique ID for artifact (e.g., "artifact_report_123")
    - details: map with keys:
      - :artifact_type - type (required, e.g., "report", "decision", "data", "model")
      - :name - human name (required)
      - :content_hash - SHA256 of content (optional)
      - :size_bytes - content size (optional)
      - :timestamp - ISO8601 creation time (optional, defaults to now)
      - :source - where artifact came from (optional)

  Returns :ok or {:error, reason}

  Example:
    emit_artifact("artifact_report_45", %{
      artifact_type: "report",
      name: "Weekly Agent Performance",
      content_hash: "abc123def456",
      size_bytes: 4096
    })
  """
  @spec emit_artifact(String.t(), map()) :: :ok | {:error, term()}
  def emit_artifact(artifact_id, details) do
    timeout = Keyword.get([timeout: @default_timeout_ms], :timeout, @default_timeout_ms)

    task =
      Task.Supervisor.async_nolink(Canopy.TaskSupervisor, fn ->
        do_emit_artifact(artifact_id, details, timeout)
      end)

    case Task.yield(task, timeout + 1000) do
      {:ok, result} ->
        result

      nil ->
        Task.shutdown(task, :brutal_kill)
        Logger.error("[OxigraphEmitter] Artifact emission timed out: #{artifact_id}")
        {:error, :timeout}
    end
  end

  @doc """
  Emit a derivation link: artifact was generated by activity.

  Records a PROV-O wasGeneratedBy triple: links artifacts to the actions that created them.
  Implements the Chatman Equation A=μ(O) by tracing artifact lineage.

  ## Parameters:
    - artifact_id: ID of the artifact
    - activity_id: ID of the activity that generated it
    - details: map with optional keys:
      - :role - role in derivation (e.g., "primary_output", "side_effect")
      - :timestamp - ISO8601 time of derivation (optional)

  Returns :ok or {:error, reason}

  Example:
    emit_derivation("artifact_report_45", "agent_7_task_1", %{
      role: "primary_output"
    })
  """
  @spec emit_derivation(String.t(), String.t(), map()) :: :ok | {:error, term()}
  def emit_derivation(artifact_id, activity_id, details \\ %{}) do
    timeout = Keyword.get([timeout: @default_timeout_ms], :timeout, @default_timeout_ms)

    task =
      Task.Supervisor.async_nolink(Canopy.TaskSupervisor, fn ->
        do_emit_derivation(artifact_id, activity_id, details, timeout)
      end)

    case Task.yield(task, timeout + 1000) do
      {:ok, result} ->
        result

      nil ->
        Task.shutdown(task, :brutal_kill)

        Logger.error(
          "[OxigraphEmitter] Derivation emission timed out: #{activity_id} -> #{artifact_id}"
        )

        {:error, :timeout}
    end
  end

  @doc """
  Query provenance lineage for an artifact.

  Returns all activities and agents involved in creating an artifact.

  ## Parameters:
    - artifact_id: ID of artifact to trace

  Returns {:ok, lineage} or {:error, reason}

  Example:
    {:ok, lineage} = query_artifact_lineage("artifact_report_45")
    # lineage = [
    #   %{activity_id: "...", agent_id: "...", action_type: "...", timestamp: "..."},
    #   ...
    # ]
  """
  @spec query_artifact_lineage(String.t()) :: {:ok, list(map())} | {:error, term()}
  def query_artifact_lineage(artifact_id) do
    query = """
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX dcterms: <http://purl.org/dc/terms/>
    PREFIX chatman: <https://ontology.chatmangpt.com/core#>

    SELECT ?activity ?agent ?action_type ?timestamp WHERE {
      <https://ontology.chatmangpt.com/artifact/#{artifact_id}> prov:wasGeneratedBy ?activity .
      ?activity prov:wasAssociatedWith ?agent ;
                chatman:actionType ?action_type ;
                dcterms:issued ?timestamp .
    }
    ORDER BY ?timestamp
    """

    case query_oxigraph(query) do
      {:ok, rows} ->
        lineage =
          Enum.map(rows, fn row ->
            %{
              activity_id: Map.get(row, "activity"),
              agent_id: Map.get(row, "agent"),
              action_type: Map.get(row, "action_type"),
              timestamp: Map.get(row, "timestamp")
            }
          end)

        {:ok, lineage}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Query all artifacts created by an agent.

  Returns list of artifact IDs and metadata created by a specific agent.

  ## Parameters:
    - agent_id: ID of agent

  Returns {:ok, artifacts} or {:error, reason}
  """
  @spec query_artifacts_by_agent(String.t()) :: {:ok, list(map())} | {:error, term()}
  def query_artifacts_by_agent(agent_id) do
    query = """
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX dcterms: <http://purl.org/dc/terms/>
    PREFIX chatman: <https://ontology.chatmangpt.com/core#>

    SELECT ?artifact ?artifact_type ?name ?timestamp WHERE {
      ?artifact prov:wasGeneratedBy ?activity ;
                rdf:type ?artifact_type ;
                chatman:name ?name ;
                dcterms:issued ?timestamp .
      ?activity prov:wasAssociatedWith <https://ontology.chatmangpt.com/agent/#{agent_id}> .
    }
    ORDER BY DESC(?timestamp)
    """

    case query_oxigraph(query) do
      {:ok, rows} ->
        artifacts =
          Enum.map(rows, fn row ->
            %{
              artifact_id: Map.get(row, "artifact"),
              artifact_type: Map.get(row, "artifact_type"),
              name: Map.get(row, "name"),
              timestamp: Map.get(row, "timestamp")
            }
          end)

        {:ok, artifacts}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # ── Private Implementation ────────────────────────────────────────────────

  defp do_emit_activity(activity_id, details, timeout_ms) do
    timestamp = Map.get(details, :timestamp) || DateTime.utc_now() |> DateTime.to_iso8601()
    agent_id = Map.get(details, :agent_id)
    action_type = Map.get(details, :action_type)

    unless agent_id and action_type do
      Logger.error(
        "[OxigraphEmitter] Missing required fields: agent_id=#{agent_id}, action_type=#{action_type}"
      )

      return_error(:missing_required_fields)
    else
      activity_uri = "<https://ontology.chatmangpt.com/activity/#{activity_id}>"
      agent_uri = "<https://ontology.chatmangpt.com/agent/#{agent_id}>"

      triples = [
        "#{activity_uri} a <http://www.w3.org/ns/prov#Activity> .",
        "#{activity_uri} <http://www.w3.org/ns/prov#wasAssociatedWith> #{agent_uri} .",
        "#{activity_uri} <https://ontology.chatmangpt.com/core#actionType> \"#{action_type}\" .",
        "#{activity_uri} <http://purl.org/dc/terms/issued> \"#{timestamp}\"^^<http://www.w3.org/2001/XMLSchema#dateTime> ."
      ]

      # Add optional fields
      triples =
        triples ++
          if Map.get(details, :duration_ms) do
            [
              "#{activity_uri} <https://ontology.chatmangpt.com/core#duration_ms> #{Map.get(details, :duration_ms)} ."
            ]
          else
            []
          end ++
          if Map.get(details, :status) do
            [
              "#{activity_uri} <https://ontology.chatmangpt.com/core#status> \"#{Map.get(details, :status)}\" ."
            ]
          else
            []
          end ++
          if Map.get(details, :input) do
            [
              "#{activity_uri} <https://ontology.chatmangpt.com/core#hasInput> \"#{escape_string(Map.get(details, :input))}\" ."
            ]
          else
            []
          end ++
          if Map.get(details, :output) do
            [
              "#{activity_uri} <https://ontology.chatmangpt.com/core#hasOutput> \"#{escape_string(Map.get(details, :output))}\" ."
            ]
          else
            []
          end

      sparql = """
      PREFIX prov: <http://www.w3.org/ns/prov#>
      PREFIX dcterms: <http://purl.org/dc/terms/>
      PREFIX chatman: <https://ontology.chatmangpt.com/core#>
      PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

      INSERT DATA {
        #{Enum.join(triples, "\n        ")}
      }
      """

      case insert_triples(sparql, timeout_ms) do
        :ok ->
          Logger.debug("[OxigraphEmitter] Recorded activity: #{activity_id}")
          :ok

        {:error, reason} ->
          Logger.error("[OxigraphEmitter] Failed to emit activity: #{inspect(reason)}")
          {:error, reason}
      end
    end
  end

  defp do_emit_artifact(artifact_id, details, timeout_ms) do
    timestamp = Map.get(details, :timestamp) || DateTime.utc_now() |> DateTime.to_iso8601()
    artifact_type = Map.get(details, :artifact_type)
    name = Map.get(details, :name)

    unless artifact_type and name do
      Logger.error(
        "[OxigraphEmitter] Missing required fields: artifact_type=#{artifact_type}, name=#{name}"
      )

      return_error(:missing_required_fields)
    else
      artifact_uri = "<https://ontology.chatmangpt.com/artifact/#{artifact_id}>"
      type_uri = "<https://ontology.chatmangpt.com/artifact/#{artifact_type}>"

      triples = [
        "#{artifact_uri} a <http://www.w3.org/ns/prov#Entity> .",
        "#{artifact_uri} a #{type_uri} .",
        "#{artifact_uri} <https://ontology.chatmangpt.com/core#name> \"#{escape_string(name)}\" .",
        "#{artifact_uri} <http://purl.org/dc/terms/issued> \"#{timestamp}\"^^<http://www.w3.org/2001/XMLSchema#dateTime> ."
      ]

      # Add optional fields
      triples =
        triples ++
          if Map.get(details, :content_hash) do
            [
              "#{artifact_uri} <https://ontology.chatmangpt.com/core#contentHash> \"#{Map.get(details, :content_hash)}\" ."
            ]
          else
            []
          end ++
          if Map.get(details, :size_bytes) do
            [
              "#{artifact_uri} <https://ontology.chatmangpt.com/core#sizeBytes> #{Map.get(details, :size_bytes)} ."
            ]
          else
            []
          end ++
          if Map.get(details, :source) do
            [
              "#{artifact_uri} <https://ontology.chatmangpt.com/core#source> \"#{escape_string(Map.get(details, :source))}\" ."
            ]
          else
            []
          end

      sparql = """
      PREFIX prov: <http://www.w3.org/ns/prov#>
      PREFIX dcterms: <http://purl.org/dc/terms/>
      PREFIX chatman: <https://ontology.chatmangpt.com/core#>
      PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

      INSERT DATA {
        #{Enum.join(triples, "\n        ")}
      }
      """

      case insert_triples(sparql, timeout_ms) do
        :ok ->
          Logger.debug("[OxigraphEmitter] Recorded artifact: #{artifact_id}")
          :ok

        {:error, reason} ->
          Logger.error("[OxigraphEmitter] Failed to emit artifact: #{inspect(reason)}")
          {:error, reason}
      end
    end
  end

  defp do_emit_derivation(artifact_id, activity_id, details, timeout_ms) do
    timestamp = Map.get(details, :timestamp) || DateTime.utc_now() |> DateTime.to_iso8601()
    role = Map.get(details, :role, "output")

    artifact_uri = "<https://ontology.chatmangpt.com/artifact/#{artifact_id}>"
    activity_uri = "<https://ontology.chatmangpt.com/activity/#{activity_id}>"

    triples = [
      "#{artifact_uri} <http://www.w3.org/ns/prov#wasGeneratedBy> #{activity_uri} .",
      "#{artifact_uri} <https://ontology.chatmangpt.com/core#derivationRole> \"#{role}\" .",
      "#{artifact_uri} <http://purl.org/dc/terms/issued> \"#{timestamp}\"^^<http://www.w3.org/2001/XMLSchema#dateTime> ."
    ]

    sparql = """
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX dcterms: <http://purl.org/dc/terms/>
    PREFIX chatman: <https://ontology.chatmangpt.com/core#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

    INSERT DATA {
      #{Enum.join(triples, "\n      ")}
    }
    """

    case insert_triples(sparql, timeout_ms) do
      :ok ->
        Logger.debug("[OxigraphEmitter] Recorded derivation: #{activity_id} -> #{artifact_id}")
        :ok

      {:error, reason} ->
        Logger.error("[OxigraphEmitter] Failed to emit derivation: #{inspect(reason)}")
        {:error, reason}
    end
  end

  defp insert_triples(sparql, timeout_ms) do
    case query_oxigraph(sparql, timeout_ms, :insert) do
      {:ok, _} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  defp query_oxigraph(sparql, timeout_ms \\ @default_timeout_ms, operation \\ :select)

  defp query_oxigraph(sparql, timeout_ms, :insert) do
    url = "#{@oxigraph_url}/store/sparql"

    try do
      case Req.post(url,
             body: sparql,
             headers: [{"content-type", "application/sparql-update"}],
             timeout: timeout_ms
           ) do
        {:ok, %{status: 200}} ->
          {:ok, nil}

        {:ok, %{status: status, body: body}} ->
          {:error, {:oxigraph_error, status, body}}

        {:error, reason} ->
          {:error, reason}
      end
    catch
      :exit, {:timeout, _} ->
        Logger.error("[OxigraphEmitter] Oxigraph query timed out after #{timeout_ms}ms")
        {:error, :timeout}
    end
  end

  defp query_oxigraph(sparql, timeout_ms, :select) do
    url = "#{@oxigraph_url}/query"

    try do
      case Req.post(url,
             body: sparql,
             headers: [
               {"content-type", "application/sparql-query"},
               {"accept", "application/json"}
             ],
             timeout: timeout_ms
           ) do
        {:ok, %{status: 200, body: %{"results" => %{"bindings" => rows}}}} ->
          rows_mapped =
            Enum.map(rows, fn row ->
              Enum.into(row, %{}, fn {k, v} ->
                {k, extract_rdf_value(v)}
              end)
            end)

          {:ok, rows_mapped}

        {:ok, %{status: 200, body: body}} ->
          {:error, {:oxigraph_parse_error, body}}

        {:ok, %{status: status, body: body}} ->
          {:error, {:oxigraph_error, status, body}}

        {:error, reason} ->
          {:error, reason}
      end
    catch
      :exit, {:timeout, _} ->
        Logger.error("[OxigraphEmitter] Oxigraph query timed out after #{timeout_ms}ms")
        {:error, :timeout}
    end
  end

  defp extract_rdf_value(%{"type" => "uri", "value" => value}), do: value
  defp extract_rdf_value(%{"type" => "literal", "value" => value}), do: value
  defp extract_rdf_value(%{"value" => value}), do: value
  defp extract_rdf_value(other), do: other

  defp escape_string(str) when is_binary(str) do
    str
    |> String.replace("\"", "\\\"")
    |> String.replace("\n", "\\n")
    |> String.replace("\r", "\\r")
    |> String.replace("\t", "\\t")
  end

  defp escape_string(other), do: inspect(other)

  defp return_error(reason), do: {:error, reason}
end
